services:
  db:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: corporate
      POSTGRES_USER: corporate_user
      POSTGRES_PASSWORD: corporate_password

    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U corporate_user -d corporate"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: corporate
      DB_USER: corporate_user
      DB_PASSWORD: corporate_password
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
