apiVersion: v1
kind: ConfigMap
metadata:
  name: corporate-data-config
data:
  DB_HOST: "host.docker.internal"
  DB_PORT: "5432"
  DB_NAME: "corporate"
  DB_USER: "corporate_user"
  APP_ENV: "kubernetes"
