apiVersion: apps/v1
kind: Deployment
metadata:
  name: corporate-data-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: corporate-data-app
  template:
    metadata:
      labels:
        app: corporate-data-app
    spec:
      containers:
        - name: corporate-data-app
          image: corporate-data-app:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: corporate-data-config
          env:
            - name: DB_PASSWORD
              value: "corporate_password"

