apiVersion: v1
kind: Pod

metadata:
  name: corporate-data-pod

spec:
  containers:
    - name: corporate-data-app
      image: corporate-data-app:2.0
      imagePullPolicy: IfNotPresent

      ports:
        - containerPort: 8000

      env:
        - name: DB_HOST
          value: "host.docker.internal"

        - name: DB_PORT
          value: "5432"

        - name: DB_NAME
          value: "corporate"

        - name: DB_USER
          value: "corporate_user"

        - name: DB_PASSWORD
          value: "corporate_password"