apiVersion: v1
kind: Service
metadata:
  name: corporate-data-service
spec:
  type: ClusterIP
  selector:
    app: corporate-data-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
